export enum ExceptionsConstants {
  FAILED_TO_DELETE_USER = 'exceptions:FAILED_TO_DELETE_USER',
  FAILED_TO_CREATE_USER = 'exceptions:FAILED_TO_CREA_USER',
  FAILED_TO_UPDATE_EMAIL = 'exceptions: FAILED_TO_UPDATE_EMAIL',
  FAILED_TO_FORGOT_PASSWORD = 'exceptions:FAILED_TO_FORGOT_PASSWORD'
}
